#!/usr/bin/env bash
# Script qui change localhost en 127.0.0.2 et facebook.com en 8.8.8.8

# Changer localhost en 127.0.0.2
sudo sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts

# Supprimer les anciennes lignes facebook.com si elles existent
sudo sed -i '/facebook\.com/d' /etc/hosts

# Ajouter la nouvelle ligne
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
