#!/usr/bin/env bash
# Script qui change l'adresse IP locale, et de facebook

sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
